project_id = "oqewofrmwxcbngmokyps"

[functions.geocode]
verify_jwt = false

[functions.maps-key]
verify_jwt = false

[functions.bulk-campaign-worker]
verify_jwt = false

[functions.ihub-webhook]
verify_jwt = false

[functions.ihub-link]
verify_jwt = false

[functions.ihub-link-v2]
verify_jwt = false
